apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.back.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{.Values.back.name}}
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.back.secret.path }}
      metadataPolicy: None
      property: dbpassword

