apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.back.name }}
spec:
  type: {{ .Values.back.service.type }}
  ports:
    - port: {{ .Values.back.service.port }}
      targetPort: {{ .Values.back.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.back.name }}
