variables:
  PROJECT_NAME: "minds-saas-rgpd-api"

include:
  - component: $CI_SERVER_FQDN/commun/components/framework/spring-boot@72be0466d1fa5ac83e46e58a606bc610ca099251
    inputs:
      app_name: "$PROJECT_NAME"
      image_name: "projets/minds-rgpd/$PROJECT_NAME"
      host_suffix: "host-suffix-rgpd"
      version: $CALCULATED_VERSION
      namespace: $TARGET_NAMESPACE
stages:
  - build

build:
  image: srv-nexus.domaine.local:18444/outillage/maven:3.9.5-jdk21-dind 