###########################
# OBLIGATOIRE
###########################
# La cle du projet "sonar".
# Cette cle doit être unique
# Si le projet existe déjà dans Sonarqube, il faut utiliser la cle existante, elle sera créée le cas échéant
sonar.projectKey=minds-rgpd-api
 
# Le nom du projet qui va être afficher sur l'UI de SonarQube
sonar.projectName=minds-rgpd-api

# La version de l'application analysée (un tag avec cette version sera créée dans Sonarqube pour la retrouver plus facilement)
sonar.projectVersion=${PROJECT_VERSION}
 
# Liste des rÃ©pertoires/fichiers à analyser, à séparer par des virgules.
# Le point correspond au rÃ©pertoire courant
sonar.sources=src/main/java
sonar.language=java
sonar.java.binaries=target/classes
# sonar.exclusions=target,\
# src/main/java/com/minds/catalog/infrastructure/security/SslConfig.java,\
# src/main/java/com/minds/catalog/MindsCatalogApplication.java

# TESTS
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.tests=src/test/java
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports

# Support lombok annotation
sonar.java.libraries=${env.HOME}/.m2/repository/org/projectlombok/lombok/**/*.jar
sonar.token=sqp_45abd144bc174d76292e1b443013e0ffca160bc5


