###########################
# OBLIGATOIRE
###########################
# La cle du projet "sonar".
# Cette cle doit �tre unique
# Si le projet existe d�j� dans Sonarqube, il faut utiliser la cle existante, elle sera cr��e le cas �ch�ant
sonar.projectKey=minds-rgpd-api
 
# Le nom du projet qui va �tre afficher sur l'UI de SonarQube
sonar.projectName=minds-rgpd-api

# La version de l'application analys�e (un tag avec cette version sera cr��e dans Sonarqube pour la retrouver plus facilement)
sonar.projectVersion=${PROJECT_VERSION}
 
# Liste des r�pertoires/fichiers � analyser, � s�parer par des virgules.
# Le point correspond au r�pertoire courant
sonar.sources=src/main/java
sonar.language=java
sonar.java.binaries=target/classes
 sonar.exclusions=target,\
  src/main/java/com/minds/rgpd/infrastructure/security/**, \
  src/main/java/com/minds/rgpd/RgpdApplication.java

# TESTS
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.tests=src/test/java
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports

# Support lombok annotation
sonar.java.libraries=${env.HOME}/.m2/repository/org/projectlombok/lombok/**/*.jar
sonar.verbose=false