spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/docker
    username: docker
    password: docker
  flyway:
    user: docker
    password: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://sso.minds.k8s/auth/realms/minds-rgpd}
          jwk-set-uri: ${JWT_JWK_SET_URI:https://sso.minds.k8s/auth/realms/minds-rgpd/protocol/openid-connect/certs}
application:
  allowed-origins: "http://localhost:4200"
  fichier.upload.dir: "."
  keycloak:
    enabled: ${KEYCLOAK_SYNC_ENABLED:true}
    base-url: ${KEYCLOAK_BASE_URL:https://sso.minds.k8s/auth}
    realm: ${KEYCLOAK_REALM:minds-rgpd}
    admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:minds-saas-rgpd-admin}
    admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
    resource-client-id: ${KEYCLOAK_RESOURCE_CLIENT_ID:minds-saas-rgpd}
    desactiver-verification-ssl: ${KEYCLOAK_DESACTIVER_VERIFICATION_SSL:true}

management:
  tracing:
    enabled: false

otel:
  sdk:
    disabled: true


#server:
#  ssl:
#    trust-store-type: NONE

# Optional: For debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG