spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/docker
    username: docker
    password: docker
  flyway:
    user: docker
    password: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.minds.k8s/auth/realms/minds-rgpd
          jwk-set-uri: https://sso.minds.k8s/auth/realms/minds-rgpd/protocol/openid-connect/certs
application:
  allowed-origins: "http://localhost:4200"
  fichier.upload.dir: "."

management:
  tracing:
    enabled: false

otel:
  sdk:
    disabled: true


#server:
#  ssl:
#    trust-store-type: NONE

# Optional: For debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG